//! Spore — a tiny, stack-based language for AI-generated embedded programs.
//!
//! Inspired by Forth, designed to be generated by AI (not written by humans).
//! The VM fits in <8KB of code and runs on `no_std` bare-metal targets.

#![no_std]

pub mod value;
pub mod op;
pub mod stack;
pub mod vm;
pub mod task;
pub mod dict;
pub mod strings;
pub mod buffer;
pub mod parse;
pub mod platform;

/// VM error type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VmError {
    StackOverflow,
    StackUnderflow,
    TypeMismatch,
    DivisionByZero,
    PlatformError,
    UnknownWord,
    ProgramEnd,
    StringPoolFull,
    BufferPoolFull,
    DictFull,
    TooManyTasks,
    TooManyEvents,
    ProgramTooLarge,
    ParseError,
}

/// An action the VM requests the scheduler to perform.
///
/// The VM cannot directly manipulate tasks — it pushes actions into a
/// small queue that the scheduler drains after each tick.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VmAction {
    /// Start a task by name (string pool index).
    StartTask(u16),
    /// Stop a task by name (string pool index).
    StopTask(u16),
    /// Emit an event (event_id = string pool index).
    EmitEvent(u16),
    /// Register an event binding: event_id → word program offset.
    BindEvent { event_id: u16, word_offset: u16 },
}

// Re-exports
pub use op::Op;
pub use platform::Platform;
pub use value::Value;
pub use vm::{StepResult, Vm};
pub use task::{Scheduler, Task, TaskState};
pub use dict::Dict;
pub use strings::StringPool;
pub use buffer::BufferPool;
pub use parse::parse;
